theme = "blowfish"
baseURL = "https://blogview.jyzh.org/"
defaultContentLanguage = "zh-cn"
title = "an zao's Blog"

enableRobotsTXT = true
summaryLength = 30
hasCJKLanguage = true

buildDrafts = false
buildFuture = false

enableEmoji = true

[pagination]
  pagerSize = 10

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'always'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 0
  toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "series"
        weight = 50

    [[related.indices]]
        name = "authors"
        weight = 20

    [[related.indices]]
        name = "date"
        weight = 10

[params]
  colorScheme = "blowfish"
  defaultAppearance = "dark"
  autoSwitchAppearance = true
  enableSearch = true
  enableCodeCopy = true

  [params.header]
    layout = "basic"

  defaultFeaturedImage = "default-featured.jpg"

  [params.homepage]
    layout = "background"
    homepageImage = "homepage-bg.jpg"
    showRecent = true
    showRecentItems = 6
    cardView = true
    cardViewScreenWidth = false

  [params.list]
    cardView = true
    cardViewScreenWidth = false
    groupByYear = true

  [params.article]
    showDate = true
    showReadingTime = true
    showWordCount = true
    showAuthor = true
    showHero = true
    heroStyle = "basic"
